CONNECTION_HOST = ""
CONNECTION_PORT = 80
CONNECTION_USER = ""
CONNECTION_PASSWORD = ""
CONNECTION_DATABASE = ""

SQL_PATH = ""
DIALECT = ""
DEFAULT_DIALECT = "ansi"

ITERATIONS = 10
OUTPUT_FILE = ""

CLIENT = ""
